myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    #url(r'^admin/', include(admin.site.urls))
    url(r'^', include('shop.urls', namespace='shop'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views


urlpaterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural='categories'

def __str__(self):
    return self.name

def get_absolute_url(self):
    return reverse('shop:product_list_by_category',args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image =models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description =models.TextField(blank=True)
    price =models.DecimalField(max_digits=10, decimal_places=2)
    stock =models.PositiveIntegerField()
    available =models.BooleanField(default=True)
    created =models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Meta:
    ordering = ('-created',)
    index_together = (('id'),('slug'),)

def __str__(self):
    return self.name

def get_absolute_url(self):
    return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render




def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'shop/product/list.html', {'category':category,
                                                          'categories': categories,
                                                          'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                  'cart_product_form': cart_product_form})

shop/templates/shop/Products/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ categry.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
      <div id="sidebar">
          <h3>Categories</h3>
          <ul>
                  <li {% if not category %}class="selected"{% endif %}>
                        <a href="{% url "shop:product_list" %}">All</a>
                  </li>
            {% for c in categories %}
                  <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                  </li>
            {% endfor %}
          </ul>
        </div>

        <div id="main" class="product-list">
          <h1> {% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
          {% for product in products %}
              <div class="item">
                    <a href="{{ product.get_absolute_url }}">
                      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static %}"
                    </a>
                    <a href="{{ product.get_absolute_url }}">{{ product.name}}</a><br>
                    ${{ product.price }}
              </div>
          {% endfor %}
        </div>
      {% endblock %}

      

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>

<body>
  <div id="header">
    <a href="/" class="logo">My shop</a>
  </div>

  <div<
    id="subheader">
    <div> class ="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                    Your cart:
                    <a href="{% url "cart:cart_detail" %}">
                      {{ total_items}} item{{ total_items|pluralize }},${{ cart.get_total_items}}
                    </a>
            {% else %}
                    Your cart is empty.
            {% endif %}
        {% endwith %}
    </div>
  </div>

  <div id="content">
        {% block content %}
        {% endblock %}
  </div>
</body>
</html>